version: '3.7'

services:
  postgres:
    container_name: postgres_arduino
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-arduino_node}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-arduino_node}
      POSTGRES_DB: ARDUINO
      PGDATA: /data/postgres
    volumes:
      - postgres_arduino:/data/postgres
    ports:
      - '5431:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres_arduino:
